### ISSUE TITLE
The external id in DB does not fit the given value in xml - external id cannot be updated.

### ISSUE THREAD

**Issue by SWade193** [ExLibrisGroup/alma-csv-user-load#104]
Could someone please elaborate on the meaning of this error message? 

Failed: The external id in DB does not fit the given value in xml - external id cannot be updated.

I am uploading user data from CSV. I get this message on some of the accounts and I can't seem to figure out a pattern. About a third of the accounts upload just fine, and most of the remaining accounts show this error message in the log. The profile type is Add/Update and the User Type is external. These are users that were successfully uploaded from CSV at one point, but now can't be updated.

Does external id refer to the Primary id? What do DB and xml refer to?

Thanks in advance!

**Comment by mgobat** [comment]
Hi @SWade193. Could you please provide an example csv file (with sensitive fields anonymized) and your import profile? You can export your import profile from the "Share" button in the Alma CSV User Load Cloud App. Thank you.

**Comment by SWade193** [comment]
Thanks so much for your reply! I have attached the CSV file with names and
emails removed, our user import profile, and a portion of the error log
with names removed.

*Steven Wade* (he/him/his)
Electronic Resources Librarian
University of Lynchburg
***@***.***
434-544-8260
Schedule an appointment with me
<https://lynchburg.libcal.com/appointments/steven>

**Comment by mgobat** [comment]
@SWade193, I don't see the attachments on the issue....

**Comment by SWade193** [comment]
Sorry! I replied by email and I guess the attachments didn't go through. Here they are:

[Error log.docx](https://github.com/user-attachments/files/18102116/Error.log.docx)
[test.csv](https://github.com/user-attachments/files/18102117/test.csv)
[User import (Badge ID).json](https://github.com/user-attachments/files/18102118/User.import.Badge.ID.json)

**Comment by mgobat** [comment]
@SWade193, do the users for which you get the error message already have an external system id? It looks like Alma generates this message when the existing external id does not match the external id provided in the update. Since your CSV file doesn't have a column for the external id, I think Alma wants to set the external id to CSV for everyone in the input file.

**Comment by SWade193** [comment]
Thank you so much! I think this is the source of our problems. Yes, users with the error message have older ids. I think what confused me is that this field is called External System Code in the upload profile and is referred to as Owner on the user details page in Alma.

The simplest thing going forward would be to update all users to have CSV as their external system id. Is there a way to do this through the CSV user load app? I have not been able to edit that field directly in Alma, but I've opened a support ticket with ExLibris to see if there is a way.

**Comment by mgobat** [comment]
I don't think the Cloud App can do that. Its really more than the Cloud App. Alma is generating the error you are getting; I think Alma just doesn't want to update an external user id...since it is external and shouldn't be under Alma's control. Alma/Cloud App should be able to set the value once on load, which it appears to do correctly for the other users in the CSV file.

See what Support says about editing the field directly in Alma. If there is some way to get Alma to do it, we might be able to figure out a way to get the Cloud App to do it.
