### ISSUE TITLE
Enhancement: Update/Add identifiers individually

### ISSUE THREAD

**Issue by BarbaraSalfate** [ExLibrisGroup/alma-csv-user-load#71]
Hi,
We want to ask an enhancement for the app:
We want to update or add only one identifier without update/delete the others identifiers from the user.
Now the update process is "swap all" - any fields provided in the input are replaced in the user record.
Thanks,
Bárbara

**Comment by cindywanghui01** [comment]
@mgobat Is there any estimate on this enhancement? Thanks!

BR,
Cindy

**Comment by mgobat** [comment]
@cindywanghui01, no timeline yet. This enhancement requires updates to Alma's APIs; it is not just a Cloud App enhancement.

**Comment by mgobat** [comment]
Hi @cindywanghui01, @Pavy317...

How important is the ability to delete and update existing identifiers for users? Is this something done regularly? 

Would adding a new profile type, maybe labeled "Enrich", that adds new repeatable fields rather than replacing them solve the problem? Non-repeatable fields would still get replaced as currently happens. This would give the ability to add identifiers, leaving existing ones in place.

**Comment by Pavy317** [comment]
@mgobat, thanks for checking in.
In our case we submitted a ticket to ExLibris to have them create the new identifier (to allow customers to their phone as an identifier).  Once they did we were able to use them.  We were beta testing the new identifier so we were not yet pulling the information from SSO yet. I believe this feature would have been helpful during testing but would not be useful to us at this time. We finished testing and identifiers are updated through SSO.

With that said, if a library is not using an automated process to manage users, I could see this as helpful.

**Comment by cindywanghui01** [comment]
@mgobat, thanks for checking.

This is very important since some of the university accept more than one identifier for patron (barcode, student id card, which is made by Academic Affairs Office, library card). Once they want to update the identifier type, they meant to add a new type, not overlay the existing one. 

BR,
Cindy

**Comment by mgobat** [comment]
@BarbaraSalfate, not sure if you saw my previous post.

Would adding a new profile type, maybe labeled "Enrich", that adds new repeatable fields rather than replacing them solve the problem? Non-repeatable fields would still get replaced as currently happens. This would give the ability to add identifiers, leaving existing ones in place.

Thanks.

**Comment by mgobat** [comment]
We've added the ability to add identifiers to existing identifiers using the new "Enrich" profile type in version v1.7. As for editing existing identifiers, that is really outside the scope of the intent of this Cloud App. It was never intended to be a user record editor.

**Comment by cindywanghui01** [comment]
@mgobat Thanks for the update. Have checked and notice my customer for the "Enrich" profile type to add new identifiers.

BR,
Cindy
