### ISSUE TITLE
Category Type for Statistical Categories

### ISSUE THREAD

**Issue by saleenaau** [ExLibrisGroup/alma-csv-user-load#80]
In the template, there is only the option for statistical category.  We have 2 category types, Job Class, and Job Department, each has their own set of values.  When I run the app, it only selects the default value which is category "Job Department"

**Comment by mgobat** [comment]
Hi @saleenaau. I need some clarification of what you are trying to do there. I don't see Job Class as part of the standard Alma user record. Are you looking for "Job Class" to be in the list of elements to pick from for the "Name" column when defining an import profile? Thank you.

**Comment by saleenaau** [comment]
![image](https://user-images.githubusercontent.com/34348177/186746278-3614548c-38bb-4c05-bb6b-a09ae9436be2.png)
I found that we can create Category Types in Alma.  So I created type "Job Class" and "Job Description".  In the app, I can only load the Statistical Category.  I can't change the Category Types at all (so it defaults to "Job Description" which is our default setting in Alma)

**Comment by saleenaau** [comment]
I guess what I need is field name for "Category Type" (When I used the browser's Developer Tool, it is called "StatisticalType")

**Comment by mgobat** [comment]
Available in release v1.6.6, 29-Aug-2022.

**Comment by saleenaau** [comment]
Thank you!

**Comment by saleenaau** [comment]
I tested the new update but it still seems to selects the default value for the category type.

**Comment by saleenaau** [comment]
[
  {
    "name": "Job class info",
    "accountType": "EXTERNAL",
    "profileType": "UPDATE",
    "fields": [
      {
        "header": "ID.NO",
        "fieldName": "primary_id",
        "default": ""
      },
      {
        "header": "Job Title Description",
        "fieldName": "job_description",
        "default": ""
      },
      {
        "header": "Job Department Description",
        "fieldName": "user_statistic[].statistic_category.value",
        "default": ""
      },
      {
        "header": "",
        "fieldName": "user_statistic[].category_type.value",
        "default": "Job Description"
      },
      {
        "header": "Job Class Description",
        "fieldName": "user_statistic[].statistic_category.value",
        "default": ""
      },
      {
        "header": "",
        "fieldName": "user_statistic[].category_type.value",
        "default": "Job Class"
      }
    ]
  }
]

**Comment by mgobat** [comment]
@saleenaau, looks like you have some empty headers in your template. I will have to try that that test case; perhaps the code takes a different route then.

My test was pretty simple; just adding a single statistic category and a category type to an existing user:
```
PID,SC,CT
mgobat,D224,DEG
```

**Comment by mgobat** [comment]
@saleenaau, does "selects the default" mean the Category Type selected to be the default in the "Category Types" codetable rather than the default in the input csv file? If so, is it possible that you don't have the input statistical category linked to the category type in the "Statistical Categories/Types" mapping table? I'm finding that if I don't have such a mapping, the "Statistical Category" is set correctly based on the input csv, but the "Category Type" is the default set in the "Category Types" codetable.

**Comment by saleenaau** [comment]
All those fields are mapped in the Statistical Categories/Types codetable.
![image](https://user-images.githubusercontent.com/34348177/187291471-c72718f6-e00d-4dd7-b610-3981b0411d3b.png)

It is using the default value set in the User Category Type.  So when I run the app, both statistical categories have the category type "Job Description".  I did notice that the statistical category for the incorrect category type does say "...(Not Listed)".

**Comment by mgobat** [comment]
@saleenaau, hmmm...yes, that certainly looks like everything is mapped correctly. Can you supply a sample CSV input file (that doesn't give away any sensitive information)? Just the header line and a few input lines would be sufficient. Thank you.

**Comment by saleenaau** [comment]
The "(not listed)" is what I expected Alma to do.  I was just saying that that was the only difference between the 2 statistical differences.

Here is the sample CSV input file (names and ID are fake):
[AlmaEmployeesData statcode CSV.csv](https://github.com/ExLibrisGroup/alma-csv-user-load/files/9470160/AlmaEmployeesData.statcode.CSV.csv)

**Comment by mgobat** [comment]
@saleenaau, thank for the examples you've provided...and your patience. I've been trying to replicate the problem, and I haven't succeeded. Since I can't see the contents of your "Statistical Categories" and "Category Types" mapping tables, let's make sure of a few things.

Looking at your import profile, I just want to confirm that the "Job Class" and "Job Description" specified for the "default" value are the actual codes and not the descriptions in the "Category Types" code table:
`{
"header": "",
"fieldName": "user_statistic[].category_type.value",
"default": "Job Description"
},`
`{
"header": "",
"fieldName": "user_statistic[].category_type.value",
"default": "Job Class"
}`

And to confirm that the values in the 'Job Class Description" column in your csv file are the codes, not the descriptions, in the "Statistical Categories" code table:

FULL TIME FACULTY TENURED
FACULTY PART TIME
HOURLY ADMINISTRATION
FULL TIME FACULTY TENURED
FACULTY PART TIME
FACULTY PART TIME

Thank you.

**Comment by saleenaau** [comment]
I wonder if that is the problem.  I was using the description instead of the codes
These are the codes:
job_dept
job_class

The Job Class was also using the description not the codes.  So for the example:
FAC
FPT
HAD
FAC
FPT
FPT

**Comment by mgobat** [comment]
@saleenaau, yes, please try the codes and see if you have success. Thank you.

**Comment by mgobat** [comment]
@saleenaau, have you been able to test the enhancement using the codes? Thanks.

**Comment by mgobat** [comment]
Closed due to lack of feedback and the belief that it is working as expected in v1.6.6.
