### ISSUE TITLE
Replace / Remove in Identifier fields

### ISSUE THREAD

**Issue by Cong81** [ExLibrisGroup/alma-csv-user-load#89]
Dear team,

I'd like your advice because I'd like to remove or empty Identifier fields (Identifier Type, Identifier Value) using the Alma CSV User Load app. Some identifiers are added to a user account, such as Identifier ID 1; Identifier ID 2; University ID; and Barcode. I tried replacing/emptying Identifier ID 1 and Identifier ID 2 while keeping the University ID and Barcode, but it didn't work.
Please see the attachments for the error and my profile configuration.

Thank you for your help.
![config profile](https://user-images.githubusercontent.com/113650920/206667586-f02c59e7-15e3-467b-92f3-5c789d327c5c.jpg)
![Error](https://user-images.githubusercontent.com/113650920/206667595-7d8a2266-06e2-4451-8c3f-32bc6d97644b.jpg)

**Comment by Cong81** [comment]
The type identifier only works with BARCODE type. It cannot recognize other identifier types (Additional ID 1; Additional ID 2; ...). Please advise on how to set up the identifier types except for BARCODE.

**Comment by mgobat** [comment]
@Cong81, I think you are getting the errors you are getting because you have the profile type set to "Add".  If the user record is already in the system with the supplied primary ID, you should use a profile type of add/update.  You should be able to add identifiers using the "Code" for each identifier type, which may be found in Alma via "Admin > User Management > User Identifier Types".

Currently, there is no way to replace/remove identifiers. The intent of the Cloud App is a full replace, not individual field editing. In GitHub issue #71, I proposed a new profile type, "Enrich", which would add repeatable fields to the user record rather than replacing what is already there. Identifiers is one such field. Would such an enhancement help you?
